# Generated by Django 4.2.3 on 2023-08-02 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_First_django', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advert',
            old_name='id',
            new_name='ID',
        ),
    ]
