# Generated by Django 4.2.3 on 2023-08-03 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_First_django', '0002_rename_id_advert_id'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='advert',
            table='advertisments',
        ),
    ]
