# Generated by Django 4.2.3 on 2023-08-03 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_First_django', '0003_alter_advert_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advert',
            old_name='ID',
            new_name='id',
        ),
    ]
