# Generated by Django 4.2.3 on 2023-08-24 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_First_django', '0006_advert_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена'),
        ),
    ]
